# Generated by Django 4.1.4 on 2022-12-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
    ]
